<a href="https://colab.research.google.com/github/yaesur/class/blob/master/%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%A0%95%EC%A0%9C%ED%95%98%EA%B8%B0_%EC%8B%A4%EC%8A%B5_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

열 삭제하기

In [ ]:
import gdown #마지막 언네임드 :,번호 : 등록일자

gdown.download('https://bit.ly/3RhoNho', 'ns_202104.csv', quiet = False)

Downloading...
From: https://bit.ly/3RhoNho
To: /content/ns_202104.csv
100%|██████████| 57.6M/57.6M [00:00<00:00, 103MB/s]

'ns_202104.csv'

In [ ]:
import pandas as pd

ns_df = pd.read_csv('ns_202104.csv', low_memory = False)
ns_df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [ ]:
ns_book = ns_df.loc[:, '번호':'등록일자']

ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19

갖고오기 불편하니까 불리언 배열
컬럼을 줄지어서 뭐가 나오는지 보기 위함

이미 배운 loc메서드에 슬라이싱을 사용하면 다음과 '번호'열부터 '등록일자'열까지 선택하여 새로운 데이터프레임을 만들 수 있다

이 방법이 편리하긴 하지만 중간에 있는 '부가기호'열을 제외하고 선택하려면 어떻게 해야할까요? 중간에 있는 열을 제외하려면 슬라이싱을 사용하기 어렵다. 이럴 때는 불리언배열 boolean array을 사용하면 쉽게 원하는 열만 선택할 수 있다

In [ ]:
print(ns_df.columns)

Index(['번호', '도서명', '저자', '출판사', '발행년도', 'ISBN', '세트 ISBN', '부가기호', '권',
       '주제분류번호', '도서권수', '대출건수', '등록일자', 'Unnamed: 13'],
      dtype='object')

In [ ]:
print(ns_df.columns[0])

번호

In [ ]:
ns_df.columns != 'Unnamed: 13'

# unnamed: 13 원소별 비교

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False])

원소별 비교를 활용하여 'Unnamed: 13'열이 아닌 것을 표시하는 배열을 만들면 위와 같다. 결과는 넘파이배열 Numpy array입니다. 지금은 넘파이 배열을 파이썬 리스트와 비슷한 것으로 생각해도 좋다. 원소별 비교 연산으로 불리언 배열을 얻었다. 이를 selected_columns 변수에 저장하고 판다스 데이터프레임의 loc메서드에 전달하면 True인 열의 행만 선택할 수 있다

In [ ]:
selected_columns = ns_df.columns != 'Unnamed: 13'
ns_book = ns_df.loc[:, selected_columns]

ns_book.head()

# Unnamed: 13 을 제한 걸로 df 만듦 *분리형 배열 이용

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19

In [ ]:
selected_columns = ns_df.columns != '부가기호'
ns_book = ns_df.loc[:, selected_columns]

ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [ ]:
ns_book = ns_df.drop('Unnamed: 13', axis = 1)

ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19

In [ ]:
ns_book = ns_df.drop(['부가기호','Unnamed: 13'], axis = 1)

ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,1,0,2021-03-19

 지금까지는 ns_df 데이터프레임에서 열을 삭제한 결과를 ns_book이라는 변수에 저장, drop() 메서드에 inplace 매개변수를 True로 지정하면 현재 선택한 데이터프레임을 바로 수정할 수 있음, 앞서 생성한 ns_book데이터프레임의 '주제분류번호'열을 삭제해보자

In [ ]:
ns_book.drop('주제분류번호', axis = 1, inplace = True)
# 선택한 데이터프레임에 덮어씀
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,권,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,1,0,2021-03-19

In [ ]:
print(ns_book.columns)

Index(['번호', '도서명', '저자', '출판사', '발행년도', 'ISBN', '세트 ISBN', '권', '도서권수',
       '대출건수', '등록일자'],
      dtype='object')

새로운 변수를 만들어 데이터프레임 수정 결과를 반환하지 않고도 ns_book 데이터프레임에서 '주제분류번호'열을 삭제

판다스는 비어있는 값을 NaN으로 표시됩니다 drop()메서드와 비슷한 dropna()메서드는 기본적으로 NaN이 하나 이상 포함된 행이나 열을 삭제, axis = 1로 지정하여 ns_df데이터프레임에서 NaN이 포함된 열을 삭제, 14개의 열이 5개로 확 줄어들었다 삭제된 열에는 NaN이 적어도 하나 이상 있었나봅니다.

In [ ]:
ns_book = ns_df.dropna(axis = 1)

ns_book.head()

   번호           ISBN  도서권수  대출건수        등록일자
0   1  9788937444319     1     0  2021-03-19
1   2  9791190123969     1     0  2021-03-19
2   3  9788968332982     1     0  2021-03-19
3   4  9788970759906     1     0  2021-03-19
4   5  9788934990833     1     0  2021-03-19

모든 값이 NaN인 열을 삭제하려면 dropna()메서드에 how매개변수를 'all'로 지정하면 됩니다

In [ ]:
ns_book = ns_df.dropna(axis = 1, how ='all')

ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19

지금까지 열을 삭제하는 방법을 알아봤다. loc메서드로 필요한 열을 선택하려면 슬라이스 연산자나 불리언 배열을 사용할 수 있다. 이 두가지가 유일한 방법은 아니다. drop() 메서드로 열을 삭제하려면 axis = 1과 삭제하려는 열을 지정! 삭제할 열이 여러개일 때는 열 이름을 리스트로 전달할 수 있다. 또는 dropna()메서드에 axis = 1을 저장하면 NaN이 들어있는 열을 삭제할 수 있다.

### 행 삭제하기

이번에는 행을 삭제하는 방법을 알아보겠다 행을 삭제할 때도 drop()메서드를 사용할 수 있다 axis매개변수를 0으로 지정하면 행을 삭제할 수 있지만, 기본값이 0이기 때문에 생략해도 괜찮다 처음 2개행을 삭제해보겠다

In [ ]:
ns_book2 = ns_book.drop([0,1])

ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19
5,6,처음 읽는 음식의 세계사,"미야자키 마사카츠 지음, 한세희 옮김",탐나는책,2021,9791189550370,NaN,NaN,NaN,NaN,1,0,2021-03-19
6,7,아르센 벵거 자서전 My Life in Red and White,"아르센 벵거 지음, 이성모 옮김",한즈미디어(한스미디어),2021,9791160075793,NaN,NaN,NaN,NaN,1,0,2021-03-19

In [ ]:
ns_book2 = ns_book2[2:]

ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19
5,6,처음 읽는 음식의 세계사,"미야자키 마사카츠 지음, 한세희 옮김",탐나는책,2021,9791189550370,NaN,NaN,NaN,NaN,1,0,2021-03-19
6,7,아르센 벵거 자서전 My Life in Red and White,"아르센 벵거 지음, 이성모 옮김",한즈미디어(한스미디어),2021,9791160075793,NaN,NaN,NaN,NaN,1,0,2021-03-19
7,8,쓰고 달콤한 직업,천운영 지음,마음산책,2021,9788960906679,NaN,NaN,NaN,NaN,1,0,2021-03-19
8,9,일잘러의 노션 100% 활용법,제레미 강 지음,위키북스,2021,9791158392512,NaN,NaN,NaN,NaN,1,0,2021-03-19

In [ ]:
ns_book2 = ns_book[0:2]

ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19

슬라이싱 이외에도 불리언 배열을 사용해서 행을 선택할 수 있다. 행을 선택할 때 가장 즐겨 사용하는 방법이다. 비교 연산자를 활용해 원하는 행은 True로 표시하고 제외할 행은 False로 표시한 불리언 배열을 만들어 사용! 예를 들어 출판사가 '한빛미디어'인 행만 선택해보자 비교 연산자를 사용하여 원본데이터프레임 ns_df에서 출판사가 '한빛미디어'인 행만 True인 불리언 배열을 만든다. 그 다음에 이 불리언 배열을 []연산자에 넣어준다

In [ ]:
selected_rows = ns_df['출판사'] == '한빛미디어'
ns_book2 = ns_book[selected_rows]

ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
60,61,(맛있는 디자인)프리미어 프로 CC: 쉽게 배워 제대로 써먹는 유튜브 영상 편집,"정지원,심수진,윤성우,김덕영 지음",한빛미디어,2021,9791162244029,NaN,1,2021,005.567,1,1,2021-03-15
70,71,처음 배우는 애저 (Azure Portal로 배우는 애저 도입부터 활용까지),김도균,한빛미디어,2020,9791162243695,NaN,NaN,NaN,005.74,1,1,2021-03-15
88,89,맛있는 디자인 프리미어 프로 CC 2021 - 쉽게 배워 제대로 써먹는 유튜브 영상 편집,"정지원, 심수진, 윤성우, 김덕영 (지은이)",한빛미디어,2021,9791162244029,NaN,NaN,NaN,NaN,0,0,2021-03-15
156,157,"실전 보고서 작성 기술 with 파워포인트, 워드, 한글",홍장표 지음,한빛미디어,2020,9791162243763,NaN,NaN,NaN,NaN,1,0,2021-03-12
198,199,처음 배우는 리액트 네이티브,김범준 지음,한빛미디어,2021,9791162243879,NaN,NaN,NaN,NaN,1,0,2021-03-12

In [ ]:
ns_book2 = ns_book.loc[selected_rows]

ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
60,61,(맛있는 디자인)프리미어 프로 CC: 쉽게 배워 제대로 써먹는 유튜브 영상 편집,"정지원,심수진,윤성우,김덕영 지음",한빛미디어,2021,9791162244029,NaN,1,2021,005.567,1,1,2021-03-15
70,71,처음 배우는 애저 (Azure Portal로 배우는 애저 도입부터 활용까지),김도균,한빛미디어,2020,9791162243695,NaN,NaN,NaN,005.74,1,1,2021-03-15
88,89,맛있는 디자인 프리미어 프로 CC 2021 - 쉽게 배워 제대로 써먹는 유튜브 영상 편집,"정지원, 심수진, 윤성우, 김덕영 (지은이)",한빛미디어,2021,9791162244029,NaN,NaN,NaN,NaN,0,0,2021-03-15
156,157,"실전 보고서 작성 기술 with 파워포인트, 워드, 한글",홍장표 지음,한빛미디어,2020,9791162243763,NaN,NaN,NaN,NaN,1,0,2021-03-12
198,199,처음 배우는 리액트 네이티브,김범준 지음,한빛미디어,2021,9791162243879,NaN,NaN,NaN,NaN,1,0,2021-03-12

In [ ]:
ns_book2 = ns_book[ns_book['대출건수'] > 1000]

ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
94781,94782,"사피엔스 :유인원에서 사이보그까지, 인간 역사의 대담하고 위대한 질문",유발 하라리 지음 ;조현욱 옮김,김영사,2016,9788934972464,NaN,NaN,NaN,909,30,1468,2016-04-22
346944,346945,해커스 토익:Listening,David Cho 지음,해커스어학연구소,2005,9788990700148,NaN,1,NaN,740.77,29,1065,2005-02-01

지금까지 불필요한 행을 삭제하거나 제외하는 방법을 알아봤습니다. 열을 삭제할 때와 마찬가지로 행을 삭제할 때도 loc메서드, drop()메서드, dropna()메서드를 모두 사용할 수 있지만, 불리언 배열을 []연산자에 전달하는 방법을 자주 사용한다는 것을 기억하세요

### 중복된 행 찾기

### 불필요한 열을 정리한 ns_book 데이터프레임에 중복된 행이 있는지 확인

In [ ]:
sum(ns_book.duplicated())

0

sum() 함수가 반환한 값이 0인 것을 보니 True로 표시된 행이 하나도 없다 중복된 행이 없다는 뜻, 이처럼 duplicated()메서드는 기본적으로 데이터프레임에 있는 모든 열을 기준으로 중복된 행을 찾는다

In [ ]:
sum(ns_book.duplicated(subset=['도서명','저자','ISBN']))

22096

사실 ns_book데이터프레임의 모든 행은 '번호'열에 고유한 값을 가지고 있기 때문에 중복된 행이 나올 수가 없습니다. 만약 '도서관','저자','ISBN'을 기준으로 중복된 행이 있는지를 찾아보면 어떨까요? 일부 열을 기준으로 중복된 행을 찾으려면 duplicated()메서드의 subset매개변수에 기준열을 나열한다 '도서명','저자','ISBN'을 기준으로 찾으면 중복된 행이 2만개가 넘는다

'도서명','저자','ISBN'을 기준으로 어떤 데이터가 중복되었는지 확인해보자 duplicated()메서드에 keep매개변수를 False로 지정하여 중복된 모든 행을 True로 표시합니다 이 데이터를 ns_book3 변수에 저장하여 확인해보자

In [ ]:
dup_rows = ns_book.duplicated(subset = ['도서명','저자','ISBN'], keep = False)
ns_book3 = ns_book[dup_rows]

ns_book3.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
109,110,파친코,이민진 지음 ;이미정 옮김,문학사상,2018,9788970129815,9788970129808,0,1,843.6,1,0,2021-03-12
110,111,파친코,이민진 지음 ;이미정 옮김,문학사상,2018,9788970129822,9788970129808,0,2,843.6,1,0,2021-03-12
111,112,보건교사 안은영 :정세랑 장편소설,지은이: 정세랑,민음사,2021,9788937479953,NaN,0,NaN,813.7,1,0,2021-03-12
112,113,보건교사 안은영 :정세랑 장편소설,지은이: 정세랑,민음사,2021,9788937479953,NaN,0,NaN,813.7,1,1,2021-03-12
113,114,스토너,존 윌리엄스 지음 ;김승욱 옮김,RHK(알에이치코리아),2021,9788925538297,NaN,0,NaN,843.5,1,0,2021-03-12

In [ ]:
count_df = ns_book[['도서명','저자','ISBN','권','대출건수']]

In [ ]:
group_df = count_df.groupby(by = ['도서명','저자','ISBN','권'], dropna = False)

loan_count = group_df.sum()

In [ ]:
loan_count = count_df.groupby(by = ['도서명','저자','ISBN','권'], dropna = False).sum()

loan_count.head()

                                                                                           대출건수
도서명                                            저자                       ISBN          권
(꼭 필요한 것부터 쉽게 배우는) 자신만만 블로그 차근차근 배우기           김상현 지음                   9788955025637 NaN    38
(맨처음 배우는) 세상의 직업                               엘레오노라 바르소티 글 ·그림 ;김태은 옮김 9788992924146 NaN    10
(영잘원 리스닝과 패턴 영어의 절묘한 만남으로 태어난 ) 리스닝 ABC : 입문편  JD Kim 지음                9788993466089 NaN     4
(즉석에서 바로바로 활용하는) 일상생활 베트남어 첫걸음                 FL4U컨텐츠 지음               9788971728000 NaN     3
,에게                                            이기린(이진희)                 9791196137014 NaN     0